---

- hosts: dev
  become: True
  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        state: present
    - name: Pip install docker-py
      pip:
        name: docker-py
        state: present
    - name: Build docker image
      docker_image:
        name: dockeransible
        build:
          path: "{{ PATH }}"
          dockerfile: Dockerfile
        source: build
        state: present
    - name: Start the container
      docker_container:
        name: dockeransible
        image: dockeransible
        state: started
        published_ports:
          - 0.0.0.0:8090:8080
