---

- hosts: localservers
  become: true
  become_user: root
  tasks:
    - name: updating repo
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present
    - name: adding repo
      shell: echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list 
    - name: installing jenkins
      apt:
        state: latest
        name:
          - jenkins
          - openjdk-11-jdk